### ISSUE TITLE
GDN with dataparallel

### ISSUE THREAD

**Issue by ZacharyGong** [jorge-pessoa/pytorch-gdn#1]
Hi,
Thank you for this implementation. 
This GDN module works well on a single GPU, but when I warp my model into the Data parallel module and use multi-GPUs to train my model, the training failed. Could you please check it?

**Comment by jorge-pessoa** [comment]
I will take a look. Can you be more specific on how the training failed?

**Comment by ZacharyGong** [comment]
Sure, I wrote a snippet to reproduce the error.
```
import torch
import torch.nn as nn
from pytorch_gdn import GDN

class Network(nn.Module):
	def __init__(self):
		super(Network, self).__init__()
		device = torch.device('cuda')
		self.conv1 = nn.Conv2d(
			in_channels=3,
			out_channels=3,
			kernel_size=3,
			stride=1,
			padding=1
		)
		self.gdn = GDN(3, device)

	def forward(self, x):
		x = self.conv1(x)
		return self.gdn(x)

cnn = Network().cuda()
gpus = [0,1]
cnn = nn.DataParallel(cnn, device_ids=gpus)

MSE = nn.MSELoss()

input = torch.rand([2,3,128,128]).cuda()
output = cnn(input)
loss = MSE(output, input)
loss.backward()
```
where I use two GPUs to run this simple cnn model, and the error message is shown as follow:
```
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    output = cnn(input)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "train.py", line 20, in forward
    return self.gdn(x)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/video/GDN_test/pytorch_gdn/__init__.py", line 76, in forward
    beta = beta**2 - self.pedestal
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:272
```
I suppose that maybe I need some kind of operations like: specify the `cuda_device id` for each chunk of data before forwarding? I'm sorry I know little about the dataparallel functionality in PyTorch.
Looking forward to your reply.

Thanks,
Gong

**Comment by ZacharyGong** [comment]
Hi,
I read the implementation carefully, and I made a few changes in the `forward` function in `class GDN` to make the code work.
```
    def forward(self, inputs):
        device_id = inputs.device.index

        beta = self.beta.to(device_id)
        gamma = self.gamma.to(device_id)
        pedestal = self.pedestal.to(device_id) 

        unfold = False
        if inputs.dim() == 5:
            unfold = True
            bs, ch, d, w, h = inputs.size() 
            inputs = inputs.view(bs, ch, d*w, h)

        _, ch, _, _ = inputs.size()

        # Beta bound and reparam
        beta = LowerBound()(beta, self.beta_bound)
        beta = beta**2 - pedestal 

        # Gamma bound and reparam
        gamma = LowerBound()(gamma, self.gamma_bound)
        gamma = gamma**2 - pedestal
        gamma  = gamma.view(ch, ch, 1, 1)

        # Norm pool calc
        norm_ = nn.functional.conv2d(inputs**2, gamma, beta)
        norm_ = torch.sqrt(norm_)
  
        # Apply norm
        if self.inverse:
            outputs = inputs * norm_
        else:
            outputs = inputs / norm_

        if unfold:
            outputs = outputs.view(bs, ch, d, w, h)
        return outputs
```
where I clone the `beta`, `gamma` and `pedestal` to the GPU where the `inputs` is stored. 
Please check the modification I made and please let me know if I did it in the right way, Thanks
